[build]
builder = "DOCKERFILE"
dockerfilePath = "eureka-server/Dockerfile"

[deploy]
startCommand = "java -jar target/eureka-server-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
