[build]
builder = "DOCKERFILE"
dockerfilePath = "cloud-gateway/Dockerfile"

[deploy]
startCommand = "java -jar target/cloud-gateway-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
